**The purpose of this notebook:** apply the clean function and attend the specific needs of the dataset to The final cleaned dataset to be used for further analysis and modeling.

In [1]:
import pandas as pd
import yaml

In [2]:
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "config").is_dir())
with open(ROOT / "config" / "config.yaml", "r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f)
cfg = {k: str(ROOT / v) for k, v in cfg.items()}  # relative paths resolve against the project root

In [3]:
P_A2_25 = pd.read_excel(cfg["P_A2_25_path"], engine="openpyxl")

In [4]:
import sys
sys.path.append(str(ROOT))  # ROOT is defined in the config cell
from src.functions import clean_plant

In [5]:
P_A2_25_clean = clean_plant(P_A2_25)
P_A2_25_clean

Rows with all NaN values: 1587
Rows with 'Dosif. m3' in first column: 1587

,\n \n Fecha,\n \n Fórmula,\n \n Volumen,"Cemento\n 1\n CEM I 42,5 R",Arido\n 1\n ARENA 04,Arido\n 2\n GRAVA 8/14,Arido\n 3\n GRAVA 12/20,Agua\n 1\n AGUA,Aditivo\n 1\n AURAMIX 269,Aditivo\n 2\n DYNAMON SX-3,Aditivo\n 4\n COMPLAST MR-,Aditivo\n 5\n AUT DINAMON
0,2025-12-30,HA-25/B/20/XC1/1,1.5,419.0,1840.0,430.0,890.0,170.0,2.7,1.9,0.0,0.0
1,2025-12-29,AUTO 300 CT-C12-F3,9.0,2269.0,15610.0,0.0,0.0,1666.0,0.0,0.0,0.0,24.8
2,2025-12-23,HA-30/F/14/XC2/1,7.0,2125.0,8500.0,5890.0,0.0,1014.0,13.5,9.5,0.0,0.0
3,2025-12-23,HA-25/B/20/XC2/1,5.0,1383.0,5900.0,1430.0,3120.0,693.0,9.0,6.2,0.0,0.0
4,2025-12-23,M-5 MD-200/P/4 SIN,1.5,300.0,2620.0,0.0,0.0,183.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1582,2025-01-21,AUTO 300 CT-C12-F3,10.0,2522.0,16920.0,0.0,0.0,2203.0,0.0,0.0,0.0,27.5
1583,2025-01-21,AUTO 300 CT-C12-F3,9.0,2263.0,15260.0,0.0,0.0,1982.0,0.0,0.0,0.0,24.8
1584,2025-01-17,AUTO 300 CT-C12-F3,6.5,1638.0,11050.0,0.0,0.0,1430.0,0.0,0.0,0.0,18.0
1585,2025-01-16,AUTO 300 CT-C12-F3,9.0,2262.0,15290.0,0.0,0.0,1982.0,0.0,0.0,0.0,24.7
1586,2025-01-16,AUTO 300 CT-C12-F3,8.0,2011.0,13440.0,0.0,0.0,1755.0,0.0,0.0,0.0,22.0

In [6]:
# How many non-zero values each column has and what percentage of all rows that represents.
non_zero_counts = (P_A2_25_clean != 0.0).sum()
non_zero_pct = non_zero_counts / len(P_A2_25_clean) * 100

pd.DataFrame({
    "non_zero_count": non_zero_counts,
    "non_zero_pct": non_zero_pct.round(2)
})

                            non_zero_count  non_zero_pct
\n \n Fecha                           1587        100.00
\n \n Fórmula                         1587        100.00
\n \n Volumen                         1587        100.00
Cemento\n 1\n CEM I 42,5 R            1575         99.24
Arido\n 1\n ARENA 04                  1575         99.24
Arido\n 2\n GRAVA 8/14                 757         47.70
Arido\n 3\n GRAVA 12/20                611         38.50
Agua\n 1\n AGUA                       1533         96.60
Aditivo\n 1\n AURAMIX 269              797         50.22
Aditivo\n 2\n DYNAMON SX-3             630         39.70
Aditivo\n 4\n COMPLAST MR-              37          2.33
Aditivo\n 5\n AUT DINAMON              512         32.26

In [7]:
P_A2_25_clean.shape

(1587, 12)

In [8]:
P_A2_25_clean.columns = [ "date", "product", "volume", "cement_42_5r", "arid_04", "arid_8_14", "arid_12_20", "water","ad_auramix","ad_dynamon_sx", "ad_complast_mr","ad_aut_dynamon"]

In [9]:
P_A2_25_clean.columns.tolist()

['date',
 'product',
 'volume',
 'cement_42_5r',
 'arid_04',
 'arid_8_14',
 'arid_12_20',
 'water',
 'ad_auramix',
 'ad_dynamon_sx',
 'ad_complast_mr',
 'ad_aut_dynamon']

In [10]:
P_A2_25_clean.shape

(1587, 12)

In [11]:
# Look at rows where cement_42_5r is zero.
P_A2_25_clean[P_A2_25_clean["cement_42_5r"] == 0]

,date,product,volume,cement_42_5r,arid_04,arid_8_14,arid_12_20,water,ad_auramix,ad_dynamon_sx,ad_complast_mr,ad_aut_dynamon
245,2025-10-23,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
247,2025-10-23,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
284,2025-10-16,AUTO 350 CT-C16-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,2025-07-11,HM-20/B/20/I/1,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
913,2025-06-10,AUTO 300 CT-C12-F3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1018,2025-05-22,AUTO 300 CT-C12-F3,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1083,2025-05-06,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1085,2025-05-06,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1496,2025-07-01,HA-25/F/14/IIa/1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1497,2025-07-01,HA-25/F/14/IIa/1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1575,2025-02-13,A-15,1.0,0.0,0.0,1600.0,0.0,0.0,0.0,0.0,0.0,0.0
1576,2025-02-13,A-15,5.0,0.0,0.0,8000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# Look at rows where arid_04 is zero.
P_A2_25_clean[P_A2_25_clean["arid_04"] == 0]

,date,product,volume,cement_42_5r,arid_04,arid_8_14,arid_12_20,water,ad_auramix,ad_dynamon_sx,ad_complast_mr,ad_aut_dynamon
245,2025-10-23,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
247,2025-10-23,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
284,2025-10-16,AUTO 350 CT-C16-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,2025-07-11,HM-20/B/20/I/1,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
913,2025-06-10,AUTO 300 CT-C12-F3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1018,2025-05-22,AUTO 300 CT-C12-F3,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1083,2025-05-06,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1085,2025-05-06,AUTO 300 CT-C12-F3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1496,2025-07-01,HA-25/F/14/IIa/1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1497,2025-07-01,HA-25/F/14/IIa/1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1575,2025-02-13,A-15,1.0,0.0,0.0,1600.0,0.0,0.0,0.0,0.0,0.0,0.0
1576,2025-02-13,A-15,5.0,0.0,0.0,8000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# The rows where the value of arid_04 and cement is 0, match. Just an observation to worth note.

In [14]:
P_A2_25_clean["product"].unique()

<ArrowStringArray>
[            'HA-25/B/20/XC1/1',           'AUTO 300 CT-C12-F3',
             'HA-30/F/14/XC2/1',             'HA-25/B/20/XC2/1',
           'M-5 MD-200/P/4 SIN',           'AUTO 350 CT-C16-F3',
             'GUNITA D-400/P/4',              'SECO MD-200/S/4',
              'HA-25/B/20/X0/1',               'HM-20/B/20/I/1',
             'HA-25/B/20/IIa/1',                'HL-150/B/20/1',
             'HA-25/B/14/IIa/1',             'HA-25/F/14/IIa/1',
             'HA-25/F/20/XC2/1',         'IMPRESO.HM-20/B/14/I',
           'M-5 MD-200/P/4 CON',               'RES.D-100/B/20',
 'PILARES  MURO HA-25/B/20/XC2',             'HA-30/F/14/XC1/1',
   'IMPRESO METRO HM-20/F/14/I',             'HA-25/F/20/XC1/1',
             'HA-25/F/14/XC2/1',         'BOMBEABLE H-150/B/20',
             'HA-25/F/14/XC1/1',             'SECO  MD-250/S/4',
             'HA-25/B/14/XC2/1',         'M-7,5 MD-250/P/4 CON',
             'HA-35/F/14/XC1/1',               'HM-20/B/14/I/1',
       'IMPRESO.HA-25/B/14/IIa',               'RES.H-150/B/20',
             'HA-30/B/20/XC2/1',       'IMPRESO.HA-25/B/20/IIa',
       'BOMBEABLE  HL-150/B/20',               'HM-20/F/14/I/1',
              'SECO D-200/S/20',             'HA-30/B/20/XS1/1',
         'IMPRESO.HM-20/F/14/I',      'PILARES  HA-25/B/20/IIa',
       'IMPRESO HA-25/B/20/XC1',             'HA-30/B/20/XC3/1',
             'HA-25/L/14/IIa/1',       'IMPRESO.HA-25/F/14/IIa',
             'HA-30/B/20/IIa/1',             'HA-30/F/14/XC4/1',
      'IMPRESO  HA-25/B/20/XC2',             'HA-30/B/20/XC4/1',
             'GUNITA D-450/P/4',      'AUTO 350 REAL D-350/L/4',
      'IMPRESO  HA-30/B/20/IIa',                         'A-15']
Length: 52, dtype: str

In [15]:
# There are different names to refer to the same products, we will standardize after merging all plants.

In [16]:
# we add a new column where all values will be P_A2 because in the future merging we need to identify from which plant the load is come from. 
# Inserting a new column, value and column position too.
P_A2_25_clean.insert(1, "plant", "P_A2")

In [17]:
P_A2_25_clean

,date,plant,product,volume,cement_42_5r,arid_04,arid_8_14,arid_12_20,water,ad_auramix,ad_dynamon_sx,ad_complast_mr,ad_aut_dynamon
0,2025-12-30,P_A2,HA-25/B/20/XC1/1,1.5,419.0,1840.0,430.0,890.0,170.0,2.7,1.9,0.0,0.0
1,2025-12-29,P_A2,AUTO 300 CT-C12-F3,9.0,2269.0,15610.0,0.0,0.0,1666.0,0.0,0.0,0.0,24.8
2,2025-12-23,P_A2,HA-30/F/14/XC2/1,7.0,2125.0,8500.0,5890.0,0.0,1014.0,13.5,9.5,0.0,0.0
3,2025-12-23,P_A2,HA-25/B/20/XC2/1,5.0,1383.0,5900.0,1430.0,3120.0,693.0,9.0,6.2,0.0,0.0
4,2025-12-23,P_A2,M-5 MD-200/P/4 SIN,1.5,300.0,2620.0,0.0,0.0,183.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,2025-01-21,P_A2,AUTO 300 CT-C12-F3,10.0,2522.0,16920.0,0.0,0.0,2203.0,0.0,0.0,0.0,27.5
1583,2025-01-21,P_A2,AUTO 300 CT-C12-F3,9.0,2263.0,15260.0,0.0,0.0,1982.0,0.0,0.0,0.0,24.8
1584,2025-01-17,P_A2,AUTO 300 CT-C12-F3,6.5,1638.0,11050.0,0.0,0.0,1430.0,0.0,0.0,0.0,18.0
1585,2025-01-16,P_A2,AUTO 300 CT-C12-F3,9.0,2262.0,15290.0,0.0,0.0,1982.0,0.0,0.0,0.0,24.7
1586,2025-01-16,P_A2,AUTO 300 CT-C12-F3,8.0,2011.0,13440.0,0.0,0.0,1755.0,0.0,0.0,0.0,22.0

In [18]:
# The final datsets (all plants and both years merged) will have the following columns in this order:
# ['date', 'plant', 'product', 'volume', 'cement_42_5r', 'cement_3a_42', 'cement_4av', 'arid_04', 'arid_8_14', 'arid_12_20', 'water', 'ad_complast_mr', 'ad_dynamon_sx', 'ad_aut_dynamon', 'ad_auramix', 'corrective_02']
# This step could be done in the merge file, but the column name need to be the same in all plants and years, so we do it here. So instead of doing just this step we order them too.
final_order = [
    'date',
    'plant',
    'product',
    'volume',
    'cement_42_5r',
    'arid_04',
    'arid_8_14',
    'arid_12_20',
    'water',
    'ad_complast_mr',
    'ad_dynamon_sx',
    'ad_aut_dynamon',
    'ad_auramix',
]

P_A2_25_clean = P_A2_25_clean[final_order]
print(P_A2_25_clean.columns.tolist())

['date', 'plant', 'product', 'volume', 'cement_42_5r', 'arid_04', 'arid_8_14', 'arid_12_20', 'water', 'ad_complast_mr', 'ad_dynamon_sx', 'ad_aut_dynamon', 'ad_auramix']

In [19]:
P_A2_25_clean.to_csv(cfg["P_A2_25_ready_csv_path"], index=False, encoding="utf-8-sig")