**The purpose of this notebook:** apply the clean function and attend the specific needs of the dataset to The final cleaned dataset to be used for further analysis and modeling.

In [2]:
import pandas as pd
import yaml

---

In [3]:
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "config").is_dir())
with open(ROOT / "config" / "config.yaml", "r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f)
cfg = {k: str(ROOT / v) for k, v in cfg.items()}  # relative paths resolve against the project root

In [4]:
P_B1_25 = pd.read_excel(cfg["P_B1_25_path"], engine="openpyxl")

---

In [5]:
import sys
sys.path.append(str(ROOT))  # ROOT is defined in the config cell
from src.functions import clean_plant

In [6]:
P_B1_25_clean = clean_plant(P_B1_25)
P_B1_25_clean

Rows with all NaN values: 1246
Rows with 'Dosif. m3' in first column: 1246

,\n \n Fecha,\n \n Fórmula,\n \n Volumen,Cemento\n 1\n CEM I 425R,Cemento\n 4\n CEM III/A 42,"Cemento\n 6\n CEM I 42,5 R",Arido\n 1\n ARENA 04,Arido\n 2\n ARIDO 8/14,Arido\n 3\n ARIDO 12/20,Arido\n 4\n ARENA CORREC,Agua\n 1\n AGUA,Aditivo\n 1\n AURAMIX 269,Aditivo\n 2\n DYNAMON SX-3
0,2025-12-30,HA-30/B/14/XC1/1,5.0,0.0,0.0,1502.0,5800.0,4240.0,0.0,0.0,744.0,12.0,5.30
1,2025-12-22,M-5 MD-200/P/4 CON ADITIVO,2.0,0.0,0.0,400.0,4080.0,0.0,0.0,0.0,200.0,2.8,0.00
2,2025-12-22,HM-20/B/20/I/1,5.0,0.0,0.0,1008.0,5760.0,2020.0,2490.0,0.0,533.0,10.1,0.00
3,2025-12-22,M-5 MD-200/P/4 CON ADITIVO,6.0,0.0,0.0,1194.0,11450.0,0.0,0.0,0.0,600.0,8.4,0.00
4,2025-12-19,HA-25/B/14/IIa/1,4.5,0.0,0.0,1280.0,5040.0,3820.0,0.0,0.0,703.0,10.3,4.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,2025-01-07,HA-30/F/20/XC2/1,6.0,0.0,1855.0,0.0,6650.0,1720.0,3600.0,0.0,835.0,9.3,13.10
1242,2025-01-07,HA-30/F/20/XC2/1,6.0,0.0,1856.0,0.0,6580.0,1730.0,3610.0,0.0,834.0,9.3,12.95
1243,2025-01-07,HA-30/F/20/XC2/1,6.0,0.0,1869.0,0.0,6700.0,1720.0,3600.0,0.0,835.0,9.3,13.00
1244,2025-01-07,HA-30/F/20/XC2/1,6.0,0.0,1856.0,0.0,6720.0,1710.0,3590.0,0.0,836.0,9.3,12.95
1245,2025-01-03,HM-20/B/20/I/1,6.0,0.0,1209.0,0.0,6620.0,2400.0,2980.0,0.0,711.0,10.9,0.00

---

In [7]:
# How many non-zero values each column has and what percentage of all rows that represents.
non_zero_counts = (P_B1_25_clean != 0.0).sum()
non_zero_pct = non_zero_counts / len(P_B1_25_clean) * 100

pd.DataFrame({
    "non_zero_count": non_zero_counts,
    "non_zero_pct": non_zero_pct.round(2)
})

                            non_zero_count  non_zero_pct
\n \n Fecha                           1246        100.00
\n \n Fórmula                         1246        100.00
\n \n Volumen                         1246        100.00
Cemento\n 1\n CEM I 425R                 1          0.08
Cemento\n 4\n CEM III/A 42             272         21.83
Cemento\n 6\n CEM I 42,5 R             946         75.92
Arido\n 1\n ARENA 04                  1219         97.83
Arido\n 2\n ARIDO 8/14                1133         90.93
Arido\n 3\n ARIDO 12/20                778         62.44
Arido\n 4\n ARENA CORREC                17          1.36
Agua\n 1\n AGUA                       1208         96.95
Aditivo\n 1\n AURAMIX 269             1178         94.54
Aditivo\n 2\n DYNAMON SX-3             957         76.81

In [8]:
P_B1_25_clean.shape

(1246, 13)

In [9]:
P_B1_25_clean.columns = ["date", "product", "volume", "cement_42_5r", "cement_3a_42", "cement_42_5r_1", "arid_04", "arid_8_14", "arid_12_20", "corrective_02","water","ad_auramix","ad_dynamon_sx"]

In [10]:
P_B1_25_clean.columns.tolist()

['date',
 'product',
 'volume',
 'cement_42_5r',
 'cement_3a_42',
 'cement_42_5r_1',
 'arid_04',
 'arid_8_14',
 'arid_12_20',
 'corrective_02',
 'water',
 'ad_auramix',
 'ad_dynamon_sx']

In [11]:
# Doing for learning purposes as alternative to the non-zero counts and percentage table. 
# Frequency of rows where cement_42_5r is non-zero.
frequency = (P_B1_25_clean["cement_42_5r"] != 0).sum()
print(f"Frequency of rows where 'cement_42_5r' is non-zero: {frequency}")

Frequency of rows where 'cement_42_5r' is non-zero: 1

In [12]:
# Show the row where cement_42_5r is non-zero.
non_zero_rows = P_B1_25_clean[P_B1_25_clean["cement_42_5r"] != 0]
print(non_zero_rows)

          date          product  volume  cement_42_5r  cement_3a_42  \
970 2025-03-04  HM-20/B/20/X0/1     7.0        1419.0           0.0

     cement_42_5r_1  arid_04  arid_8_14  arid_12_20  corrective_02  water  \
970             0.0   7660.0     2810.0      3490.0            0.0  903.0

     ad_auramix  ad_dynamon_sx
970        12.7            0.0

In [13]:
# Merging cement_42_5r and cement_42_5r_1 and drop the cement_42_5r_1 column.
P_B1_25_clean["cement_42_5r"] = P_B1_25_clean["cement_42_5r"] + P_B1_25_clean["cement_42_5r_1"]
P_B1_25_clean.drop(columns=["cement_42_5r_1"], inplace=True)

In [14]:
P_B1_25_clean.columns.tolist()

['date',
 'product',
 'volume',
 'cement_42_5r',
 'cement_3a_42',
 'arid_04',
 'arid_8_14',
 'arid_12_20',
 'corrective_02',
 'water',
 'ad_auramix',
 'ad_dynamon_sx']

In [15]:
# Frequency of rows where the condition is that product cement_42_5r and cement_3a_42 are both !=0 in the same row.
condition = (P_B1_25_clean["cement_42_5r"] != 0) & (P_B1_25_clean["cement_3a_42"] != 0)
frequency = condition.sum()
print(f"Frequency of rows where both cement_42_5r and cement_3a_42 are != 0: {frequency}")

Frequency of rows where both cement_42_5r and cement_3a_42 are != 0: 0

In [16]:
# We see that there are 0 rows where both cement_42_5r and cement_a_42 are != 0. 
# Which means that there are no loads where both of these products are present in the same row.
# So, all product with cement use cement_42_5r or cement_a_42.

In [17]:
# How many non-zero values each column has and what percentage of all rows that represents.
non_zero_counts = (P_B1_25_clean != 0.0).sum()
non_zero_pct = non_zero_counts / len(P_B1_25_clean) * 100

pd.DataFrame({
    "non_zero_count": non_zero_counts,
    "non_zero_pct": non_zero_pct.round(2)
})

               non_zero_count  non_zero_pct
date                     1246        100.00
product                  1246        100.00
volume                   1246        100.00
cement_42_5r              947         76.00
cement_3a_42              272         21.83
arid_04                  1219         97.83
arid_8_14                1133         90.93
arid_12_20                778         62.44
corrective_02              17          1.36
water                    1208         96.95
ad_auramix               1178         94.54
ad_dynamon_sx             957         76.81

In [18]:
# we add a new column where all values will be P_B1 because in the future merging we need to identify from which plant the load is come from. 
# Inserting a new column and value. 
# P_B1_25_clean["plant"] = "P_B1"
# Inserting a column position too. 
P_B1_25_clean.insert(1, "plant", "P_B1")

In [19]:
P_B1_25_clean.columns.tolist()

['date',
 'plant',
 'product',
 'volume',
 'cement_42_5r',
 'cement_3a_42',
 'arid_04',
 'arid_8_14',
 'arid_12_20',
 'corrective_02',
 'water',
 'ad_auramix',
 'ad_dynamon_sx']

In [20]:
# The final datsets (all plants and both years merged) will have the following columns in this order:
# ['date', 'plant', 'product', 'volume', 'cement_42_5r', 'cement_3a_42', 'cement_4av', 'arid_04', 'arid_8_14', 'arid_12_20', 'water', 'ad_complast_mr', 'ad_dynamon_sx', 'ad_aut_dynamon', 'ad_auramix', 'corrective_02']
# This step could be done in the merge file, but the column name need to be the same in all plants and years, so we do it here. So instead of doing just this step we order them too.
final_order = [
    'date',
    'plant',
    'product',
    'volume',
    'cement_42_5r',
    'cement_3a_42',
    'arid_04',
    'arid_8_14',
    'arid_12_20',
    'water',
    'ad_dynamon_sx',
    'ad_auramix',
    'corrective_02'
]

P_B1_25_clean = P_B1_25_clean[final_order]
print(P_B1_25_clean.columns.tolist())

['date', 'plant', 'product', 'volume', 'cement_42_5r', 'cement_3a_42', 'arid_04', 'arid_8_14', 'arid_12_20', 'water', 'ad_dynamon_sx', 'ad_auramix', 'corrective_02']

In [21]:
P_B1_25_clean

,date,plant,product,volume,cement_42_5r,cement_3a_42,arid_04,arid_8_14,arid_12_20,water,ad_dynamon_sx,ad_auramix,corrective_02
0,2025-12-30,P_B1,HA-30/B/14/XC1/1,5.0,1502.0,0.0,5800.0,4240.0,0.0,744.0,5.30,12.0,0.0
1,2025-12-22,P_B1,M-5 MD-200/P/4 CON ADITIVO,2.0,400.0,0.0,4080.0,0.0,0.0,200.0,0.00,2.8,0.0
2,2025-12-22,P_B1,HM-20/B/20/I/1,5.0,1008.0,0.0,5760.0,2020.0,2490.0,533.0,0.00,10.1,0.0
3,2025-12-22,P_B1,M-5 MD-200/P/4 CON ADITIVO,6.0,1194.0,0.0,11450.0,0.0,0.0,600.0,0.00,8.4,0.0
4,2025-12-19,P_B1,HA-25/B/14/IIa/1,4.5,1280.0,0.0,5040.0,3820.0,0.0,703.0,4.50,10.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,2025-01-07,P_B1,HA-30/F/20/XC2/1,6.0,0.0,1855.0,6650.0,1720.0,3600.0,835.0,13.10,9.3,0.0
1242,2025-01-07,P_B1,HA-30/F/20/XC2/1,6.0,0.0,1856.0,6580.0,1730.0,3610.0,834.0,12.95,9.3,0.0
1243,2025-01-07,P_B1,HA-30/F/20/XC2/1,6.0,0.0,1869.0,6700.0,1720.0,3600.0,835.0,13.00,9.3,0.0
1244,2025-01-07,P_B1,HA-30/F/20/XC2/1,6.0,0.0,1856.0,6720.0,1710.0,3590.0,836.0,12.95,9.3,0.0
1245,2025-01-03,P_B1,HM-20/B/20/I/1,6.0,0.0,1209.0,6620.0,2400.0,2980.0,711.0,0.00,10.9,0.0

---

In [22]:
P_B1_25_clean.to_csv(cfg["P_B1_25_ready_csv_path"], index=False, encoding="utf-8")